
# Run all tests: `docker-compose up --abort-on-container-exit`
# Enter console: `docker-compose run --rm --entrypoint /bin/bash nodejs` and `service sshd start`
# Run a subset of the tests: `docker-compose run --rm nodejs test/service`

# TODO: implement variable substitution once default value is implemented
# see https://github.com/docker/compose/issues/2441

version: '2'
services:
  nodejs:
    build: .
    image: nikita_mysql5_nodejs
    volumes:
      - ../..:/nikita
    depends_on:
      - mysql
    environment:
      NIKITA_TEST_MODULE: /nikita/env/mysql5/test.coffee
      DOCKER_HOST: 'tcp://dind:2375'
      TMPDIR: '/var/tmp'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootme
    expose:
      - "3306"
