
# Run all tests: `docker-compose up --abort-on-container-exit`
# Enter console: `docker-compose run --rm --entrypoint /bin/bash nodejs` and `service sshd start`
# Run a subset of the tests: `docker-compose run --rm nodejs test/service`

# TODO: implement variable substitution once default value is implemented
# see https://github.com/docker/compose/issues/2441

version: '2'
services:
  nodejs:
    build: .
    image: nikita_postgresql_nodejs
    volumes:
      - ../..:/nikita
    depends_on:
      - postgres
    environment:
      MECANO_TEST: /nikita/env/postgresql/test.coffee
      TMPDIR: '/var/tmp'
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootme
    expose:
      - "5432"
