language: node_js
node_js:
  - "10"
  - "12"
cache:
  npm: false
  yarn: true
install:
  - sudo apt remove -y --purge lxd lxd-client
  - sudo snap install lxd
  - sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment'
  - sudo lxd waitready
  - sudo lxd init --auto
  - sudo usermod -a -G lxd $USER
  - yarn install
before_script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
  - cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
  # - sudo apt-get install -y openjdk-9-jre gcc make ruby ruby-dev
  - yarn --version
  - lerna bootstrap
  - ls -l node_modules
script:
  # - lerna run test --stream
  - sudo su - $USER -c "cd `pwd` && ./packages/ipa/env/run.sh"
