
# Run all tests: `docker-compose up --abort-on-container-exit`
# Enter console: `docker-compose run --rm --entrypoint /bin/bash nodejs` and `service sshd start`
# Run a subset of the tests: `docker-compose run --rm nodejs test/service`

# TODO: implement variable substitution once default value is implemented
# see https://github.com/docker/compose/issues/2441

version: '2'
services:
  nodejs:
    build: .
    image: nikita_mariadb_nodejs
    volumes:
      - ../..:/nikita
    depends_on:
      - mariadb
    environment:
      MECANO_TEST: /nikita/docker/mariadb/test.coffee
      TMPDIR: '/var/tmp'
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootme
    expose:
      - "3306"
